### ISSUE TITLE
Weird behavior of the `uninstall` alias

### ISSUE THREAD

**Issue by tranzystorekk** [tranzystorek-io/pakr#2]
The `uninstall` alias is duplicated in `--help` output and in the completion scripts. This seems to be an upstream [bug](https://github.com/TeXitoi/structopt/issues/418) in structopt, without an apparent solution so far.

**Comment by tranzystorekk** [comment]
Might be better to port arg parsing to clap once 3.0.0 has been released and wait until https://github.com/clap-rs/clap/issues/2898 is fixed.

**Comment by epage** [comment]
In case you missed it, there is a [PR for structopt](https://github.com/TeXitoi/structopt/pull/504), I just haven't seen it get any attention

**Comment by tranzystorekk** [comment]
Fixed for now in version 0.5.1 via structopt 0.3.25 🎉

Thank you @epage for pointing out the PR! 😄
